### ISSUE TITLE
Not showing list of shows

### ISSUE THREAD

**Issue by emilkjer** [adamrumbold/SBS.bundle#1]
When launching the plugin via "Videos > SBS" no shows are shown only a black screen. I.e. not possible to play shows from SBS via the plugin.

Plex Media Server Version:  0.9.5.2-bf472e4"
Plex Client Version: 0.9.0-312c11b0

**Comment by adamrumbold** [comment]
Thanks for letting me know. Just fixed the issue with the latest commit.

**Comment by emilkjer** [comment]
great thanks, it works. Now I guess it up to me to make one for ABC and ultimately through iiNET :)

**Comment by emilkjer** [comment]
That was easy :) Already made.... http://wiki.plexapp.com/index.php/ABC_iView

On Sat, Mar 3, 2012 at 5:08 PM, Adam
reply@reply.github.com
wrote:

**Comment by adamrumbold** [comment]
Yes.  You'll find the ABC iView plugin is a supported plugin - so can be found and installed through the Plex App Store (from within the application).  ABC iView should still be unmetered in my experience :)
